name: Run Consolidated Script Daily

on:
  schedule:
    - cron: "30 14 * * 0-5"  # Runs at 8:30 PM IST (14:30 UTC) from Sunday to Friday
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Ensure the script does not exceed 1 hour

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Consolidated Script
        run: python consolidated.py

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update of mutual fund data"
          git push
        continue-on-error: true  # Prevent failure if no changes were made
